# Generated by Django 3.1.5 on 2021-02-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Setor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='blog.setor'),
        ),
    ]
