# Generated by Django 3.1.5 on 2021-02-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_product_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
