# Generated by Django 3.1.5 on 2021-02-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_setor_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Setor',
            new_name='setor',
        ),
    ]
