# Generated by Django 3.1.5 on 2021-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210215_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/images/teste.jpeg', upload_to='images/setor/'),
        ),
    ]
